参考链接：
* https://geek-docs.com/python/python-ask-answer/223_tk_1705615334.html 读取tif格式图片教程

# 如果使用cloudstudio来运行

在云编辑机底部蓝边显示休眠时间的右侧有1核2GB的字样，改为2核4GB重启，不然数据和包不够空间

## 安装

在终端里输入`conda install -c conda-forge gdal`来安装  并且在Proceed ([y]/n)? 询问是输入y再回车确认

## 数据放置

将hakui-10.tif放置在data文件夹中

## 运行jupyter选择内核：base(python3.11.4)

In [2]:
from osgeo import gdal
import numpy as np

In [4]:
dataset = gdal.Open('../../data/hakui-10.tif', gdal.GA_ReadOnly)

geotransform = dataset.GetGeoTransform()
print('地理变换信息：', geotransform)

# 获取影像的投影信息
projection = dataset.GetProjection()
print('投影信息：', projection)

# 获取影像的宽度和高度
width = dataset.RasterXSize
height = dataset.RasterYSize
print('影像尺寸：', width, 'x', height)

# 读取栅格数据
band = dataset.GetRasterBand(1)
data = band.ReadAsArray(0, 0, width, height)
print('栅格数据：', data)

# 关闭文件
dataset = None

地理变换信息： (654122.863, 1.0, 0.0, 4089847.94, 0.0, -1.0)
投影信息： PROJCS["WGS 84 / UTM zone 53N",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",135],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH],AUTHORITY["EPSG","32653"]]
影像尺寸： 6795 x 5522
栅格数据： [[-3.188606  -3.4330714 -4.196203  ... -3.0016232 -4.0146923 -4.056568 ]
 [-3.6444335 -4.2536907 -5.4488506 ... -4.4108315 -4.371334  -3.7885566]
 [-5.4034915 -6.589065  -7.8912473 ... -5.4175034 -4.598599  -3.5299885]
 ...
 [-7.5285115 -7.55757   -7.6705217 ...        nan        nan        nan]
 [-7.1720023 -6.5007

In [5]:
data.shape

(5522, 6795)

In [6]:
# 访问特定像素的值
value = data[1000, 1000]
print('像素值：', value)

# 访问整个波段的像素值
print('整个波段的像素值：', data)

像素值： -5.060918
整个波段的像素值： [[-3.188606  -3.4330714 -4.196203  ... -3.0016232 -4.0146923 -4.056568 ]
 [-3.6444335 -4.2536907 -5.4488506 ... -4.4108315 -4.371334  -3.7885566]
 [-5.4034915 -6.589065  -7.8912473 ... -5.4175034 -4.598599  -3.5299885]
 ...
 [-7.5285115 -7.55757   -7.6705217 ...        nan        nan        nan]
 [-7.1720023 -6.500743  -7.1967645 ...        nan        nan        nan]
 [-6.220325  -5.002194  -5.7345757 ...        nan        nan        nan]]
